### ISSUE TITLE
blender-2.79 git version

### ISSUE THREAD

**Issue by brothermechanic** [zeffii/TubeTool#17]
When i run tt in object mode
Is it normal?
End
Traceback (most recent call last):
  File "/usr/share/blender/2.79/scripts/addons/TubeTool-9999/tt_operators.py", line 366, in invoke
    self.initialize_new_tube(context)
  File "/usr/share/blender/2.79/scripts/addons/TubeTool-9999/tt_operators.py", line 308, in initialize_new_tube
    if not (obj_main.data.total_face_sel == 2):
AttributeError: 'NoneType' object has no attribute 'data'

location: <unknown location>:-1

**Comment by zeffii** [comment]
yes, must be in Edit Mode

**Comment by zeffii** [comment]
the options are 

1. add a test in the `poll` of the operator to do nothing if not in Edit Mode
2. allow object mode scenario, permitting polygons to be selected from two separate objects.

for users i bet the second option would open more doors..
