### ISSUE TITLE
blender 2.79 Windows 10 64 bit

### ISSUE THREAD

**Issue by reinhardp** [zeffii/TubeTool#18]
I tryed the addon with a new blend file and a cube in edit mode.
But I get the following error:

Traceback (most recent call last):
  File "C:\Users\irpag\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\TubeTool-master\tt_operators.py", line 362, in execute
    update_simple_tube(self, context)
  File "C:\Users\irpag\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\TubeTool-master\tt_operators.py", line 192, in update_simple_tube
    modify_curve(medians, normals, generated_name)
  File "C:\Users\irpag\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\TubeTool-master\tt_operators.py", line 150, in modify_curve
    obj = bpy.data.objects[generated_name]
KeyError: 'bpy_prop_collection[key]: key "" not found'

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by zeffii** [comment]
have you used the add-on before?

if not it expects an object in edit mode, with two faces only selected, then invoke the tool.

**Comment by zeffii** [comment]
also.. is it an official release blender 2.79 , or a buildbot build or what... do you know the date of the blender binary or hash ? :)

**Comment by reinhardp** [comment]
no did not used add-on before. The hash is 8928d99270f. I downloaded the binaries directly from the blender website.

**Comment by reinhardp** [comment]
I made an other test with it, but then I get the following result. And yes I used was in edit mode to add the tube.

![grafik](https://user-images.githubusercontent.com/13554602/42424457-f3f010fa-830c-11e8-9011-1508ef8d06c5.png)

**Comment by reinhardp** [comment]
Sorry, it is my fault, I used the wrong addon.
